### ISSUE TITLE
Add case-split ability

### ISSUE THREAD

**Issue by JoeyEremondi** [atom-haskell/haskell-ghc-mod#103]
This was my favorite feature when using ghc-mod with emacs: being able to put the cursor over a variable in a case-split, do M-t, and have it create the pattern match for me with all the possible constructors.

Is this currently possible with atom? If not, consider this a feature request in what's already a pretty great package.

Thanks!

**Comment by lierdakil** [comment]
No, it's not implemented at the moment, and yes, I can do that.

**Comment by lierdakil** [comment]
Sorry it took so long.

**Comment by DanielG** [comment]
Are you doing this via `ghc-mod legacy-interactive` or a separate ghc-mod invocation? There is a bug in all currently released versions that will break case splitting when you use `check` in the same session as `case-split` iirc.

**Comment by lierdakil** [comment]
Former. But that should be relatively easy to change.

**Comment by lierdakil** [comment]
I do however occasionally run into `Prelude.head: empty list` crash with case split with master.

**Comment by DanielG** [comment]
You can change it back to interactive after the next release it's just a workaround. As for that empty list crash I haven't seen that before. I see like four usages of `head` in CaseSplit.hs and some in FillSig.hs. We should probably replace them with headNote so we can identify which one is failing.

**Comment by Gurkenglas** [comment]
Selecting fromJust and invoking a command should import Data.Maybe, and there should be an option to automatically resolve not-in-scope errors by importing (and automatically remove unused imports). (Make sure not to let it move the line the cursor is on relative to the screen.)

**Comment by lierdakil** [comment]
@Gurkenglas, that is not possible in general case. Auto-imports are available, although those are work-in-progress. In any case, this is unrelated. In the future, please file separate issues.

**Comment by lierdakil** [comment]
@DanielG, apparently, it's this one: https://github.com/DanielG/ghc-mod/blob/master/Language/Haskell/GhcMod/CaseSplit.hs#L214

This happens primarily with stupid cases, e.g.

```haskell
test :: Maybe a
test x = _body
```

Running case split on `x` will crash ghc-mod then.

**Comment by DanielG** [comment]
Can you make a testcase so we can track this crash?

**Comment by lierdakil** [comment]
Um. Sure. Should I add it to case-split tests with a PR then?

**Comment by DanielG** [comment]
Sure.
