### ISSUE TITLE
Haskell-ghc-mod: ghc-mod command lang failed with error code 1

### ISSUE THREAD

**Issue by edmundcape** [atom-haskell/haskell-ghc-mod#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.6.6

### Stack Trace

Haskell-ghc-mod: ghc-mod command lang failed with error code 1

```
At caps: {"version":[5,2,1,2],"legacyInteractive":false,"fileMap":false,"rootExec":false,"quoteArgs":false,"optparse":false}
URI: undefined
Args: 
message: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/settings: openFile: does not exist (No such file or directory)

log:
-0.335s: getProcessOptions(.)
-0.326s: PATH = /Users/edmund/Library/Haskell/bin/:/usr/bin:/bin:/usr/sbin:/sbin
-0.156s: warn: nameless module in /Users/edmund/Dropbox/Programming/Haskell/src/pipes_exercise_2.hs
-0.155s: Pipes created
-0.154s: Pipes updating
-0.154s: getProcessOptions(/Users/edmund/Dropbox/Programming/Haskell/src)
-0.147s: PATH = /Users/edmund/Library/Haskell/bin/:/usr/bin:/bin:/usr/sbin:/sbin
-0.112s: Pipes moduleName mismatch: undefined != Pipes
-0.112s: Pipes.Prelude created
-0.112s: Pipes.Prelude updating
-0.086s: Pipes.Prelude moduleName mismatch: undefined != Pipes.Prelude
-0.086s: Prelude created
-0.086s: Prelude updating
-0.056s: Prelude moduleName mismatch: undefined != Prelude
-0.038s: {"version":[5,2,1,2],"legacyInteractive":false,"fileMap":false,"rootExec":false,"quoteArgs":false,"optparse":false}
-0.036s: running /Users/edmund/Library/Haskell/bin/ghc-mod lang with options.cwd = .,options.env = [object Object],options.encoding = utf-8
-0.03s: running /Users/edmund/Library/Haskell/bin/ghc-mod flag with options.cwd = .,options.env = [object Object],options.encoding = utf-8
-0.026s: running /Users/edmund/Library/Haskell/bin/ghc-mod browse,-d,Pipes with options.cwd = /Users/edmund/Dropbox/Programming/Haskell/src,options.env = [object Object],options.encoding = utf-8
-0.023s: running /Users/edmund/Library/Haskell/bin/ghc-mod browse,-d,Pipes.Prelude with options.cwd = /Users/edmund/Dropbox/Programming/Haskell/src,options.env = [object Object],options.encoding = utf-8
-0.002s: ghc-mod said: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/settings: openFile: does not exist (No such file or directory)
-0.002s: ghc-mod said: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/settings: openFile: does not exist (No such file or directory)
-0.001s: /Users/edmund/Library/Haskell/bin/ghc-mod ended with code 1
0s: code 1: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/settings: openFile: does not exist (No such file or directory)


code 1: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/settings: openFile: does not exist (No such file or directory)

    at module.exports.Util.mkError (/Users/edmund/.atom/packages/haskell-ghc-mod/lib/util.coffee:154:15)
    at BufferedProcess.exit (/Users/edmund/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.coffee:122:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-css",
      "autocomplete-html",
      "autocomplete-atom-api",
      "autocomplete-plus"
    ],
    "themes": [
      "nucleus-dark-ui",
      "gruvbox"
    ]
  },
  "haskell-ghc-mod": {
    "additionalPathDirectories": [
      "/Users/edmund/Library/Haskell/bin/"
    ],
    "ghcModPath": "/Users/edmund/Library/Haskell/bin/ghc-mod",
    "ghcModiPath": "/Users/edmund/Library/Haskell/bin/ghc-modi",
    "onMouseHoverShow": "Nothing"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
gruvbox, v1.0.5
haskell-ghc-mod, v1.6.6
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
ide-haskell-repl, v0.0.17
language-haskell, v1.5.2
nucleus-dark-ui, v0.7.4

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Your ghc installation seems to be broken. Either that, or ghc-mod was
compiled in another environment.
8 февр. 2016 г. 0:49 пользователь "edmundcape" <notifications@github.com>
написал:

**Comment by edmundcape** [comment]
Indeed.  I'm not sure how it happened, but I since rebuilt the ghc-mod
using cabal.  The version is now updated and compiled for the version of
ghci in use.  The error is now resolved.  Thank you for your help.  - E

On Mon, Feb 8, 2016 at 1:13 AM, Nikolay Yakimov <notifications@github.com>
wrote:

> Your ghc installation seems to be broken. Either that, or ghc-mod was
> compiled in another environment.
> 8 февр. 2016 г. 0:49 пользователь "edmundcape" <notifications@github.com>
> написал:
>
> > [Enter steps to reproduce below:]
> >
> > 1
> > 2
> >
> > *Atom Version*: 143
> > *System*: Mac OS X 10113
> > *Thrown From*: haskell-ghc-mod
> > <https://githubcom/atom-haskell/haskell-ghc-mod> package, v166
> > Stack Trace
> >
> > Haskell-ghc-mod: ghc-mod command lang failed with error code 1
> >
> > At caps:
> {"version":[5,2,1,2],"legacyInteractive":false,"fileMap":false,"rootExec":false,"quoteArgs":false,"optparse":false}
> > URI: undefined
> > Args:
> > message:
> /Library/Frameworks/GHCframework/Versions/783-x86_64/usr/lib/ghc-783/settings:
> openFile: does not exist (No such file or directory)
> >
> > log:
> > -0335s: getProcessOptions()
> > -0326s: PATH =
> /Users/edmund/Library/Haskell/bin/:/usr/bin:/bin:/usr/sbin:/sbin
> > -0156s: warn: nameless module in
> /Users/edmund/Dropbox/Programming/Haskell/src/pipes_exercise_2hs
> > -0155s: Pipes created
> > -0154s: Pipes updating
> > -0154s: getProcessOptions(/Users/edmund/Dropbox/Programming/Haskell/src)
> > -0147s: PATH =
> /Users/edmund/Library/Haskell/bin/:/usr/bin:/bin:/usr/sbin:/sbin
> > -0112s: Pipes moduleName mismatch: undefined != Pipes
> > -0112s: PipesPrelude created
> > -0112s: PipesPrelude updating
> > -0086s: PipesPrelude moduleName mismatch: undefined != PipesPrelude
> > -0086s: Prelude created
> > -0086s: Prelude updating
> > -0056s: Prelude moduleName mismatch: undefined != Prelude
> > -0038s:
> {"version":[5,2,1,2],"legacyInteractive":false,"fileMap":false,"rootExec":false,"quoteArgs":false,"optparse":false}
> > -0036s: running /Users/edmund/Library/Haskell/bin/ghc-mod lang with
> optionscwd = ,optionsenv = [object Object],optionsencoding = utf-8
> > -003s: running /Users/edmund/Library/Haskell/bin/ghc-mod flag with
> optionscwd = ,optionsenv = [object Object],optionsencoding = utf-8
> > -0026s: running /Users/edmund/Library/Haskell/bin/ghc-mod
> browse,-d,Pipes with optionscwd =
> /Users/edmund/Dropbox/Programming/Haskell/src,optionsenv = [object
> Object],optionsencoding = utf-8
> > -0023s: running /Users/edmund/Library/Haskell/bin/ghc-mod
> browse,-d,PipesPrelude with optionscwd =
> /Users/edmund/Dropbox/Programming/Haskell/src,optionsenv = [object
> Object],optionsencoding = utf-8
> > -0002s: ghc-mod said:
> /Library/Frameworks/GHCframework/Versions/783-x86_64/usr/lib/ghc-783/settings:
> openFile: does not exist (No such file or directory)
> > -0002s: ghc-mod said:
> /Library/Frameworks/GHCframework/Versions/783-x86_64/usr/lib/ghc-783/settings:
> openFile: does not exist (No such file or directory)
> > -0001s: /Users/edmund/Library/Haskell/bin/ghc-mod ended with code 1
> > 0s: code 1:
> /Library/Frameworks/GHCframework/Versions/783-x86_64/usr/lib/ghc-783/settings:
> openFile: does not exist (No such file or directory)
> >
> >
> > code 1:
> /Library/Frameworks/GHCframework/Versions/783-x86_64/usr/lib/ghc-783/settings:
> openFile: does not exist (No such file or directory)
> >
> > at moduleexportsUtilmkError
> (/Users/edmund/atom/packages/haskell-ghc-mod/lib/utilcoffee:154:15)
> > at BufferedProcessexit
> (/Users/edmund/atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-realcoffee:122:20)
> > at triggerExitCallback
> (/Applications/Atomapp/Contents/Resources/appasar/src/buffered-processjs:213:47)
> > at
> /Applications/Atomapp/Contents/Resources/appasar/src/buffered-processjs:227:18
> > at Socket<anonymous>
> (/Applications/Atomapp/Contents/Resources/appasar/src/buffered-processjs:98:18)
> > at emitOne (eventsjs:82:20)
> > at Socketemit (eventsjs:169:7)
> > at Pipe_onclose (netjs:469:12)
> >
> > Commands
> >
> > Config
> >
> > {
> > "core": {
> > "disabledPackages": [
> > "autocomplete-css",
> > "autocomplete-html",
> > "autocomplete-atom-api",
> > "autocomplete-plus"
> > ],
> > "themes": [
> > "nucleus-dark-ui",
> > "gruvbox"
> > ]
> > },
> > "haskell-ghc-mod": {
> > "additionalPathDirectories": [
> > "/Users/edmund/Library/Haskell/bin/"
> > ],
> > "ghcModPath": "/Users/edmund/Library/Haskell/bin/ghc-mod",
> > "ghcModiPath": "/Users/edmund/Library/Haskell/bin/ghc-modi",
> > "onMouseHoverShow": "Nothing"
> > }
> > }
> >
> > Installed Packages
> >
> > # User
> > autocomplete-haskell, v062
> > gruvbox, v105
> > haskell-ghc-mod, v166
> > ide-haskell, v139
> > ide-haskell-cabal, v100
> > ide-haskell-repl, v0017
> > language-haskell, v152
> > nucleus-dark-ui, v074
> > # DevNo dev packages
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/atom-haskell/haskell-ghc-mod/issues/109>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom-haskell/haskell-ghc-mod/issues/109#issuecomment-181213738>
> .
>



-- 

Edmund Cape, PhD MBA
(917) 715-8299
edmund.cape@gmail.com
