### ISSUE TITLE
Recompiling only on demand

### ISSUE THREAD

**Issue by trin-cz** [atom-haskell/haskell-ghc-mod#117]
Hi, when I try to rewrite some code or make a bigger change, haskell-ghc-mod starts recompiling immediately, even though the compilation has no chance to succeed.

Would it be possible to choose to trigger the recompilation explicitly somehow - with a keybinding perhaps?

**Comment by lierdakil** [comment]
There is no "recompilation" going on, just parsing and type-checking. So I'm not sure I understand your question correctly. Anyway, you can disable "check on save" and "check on change" in haskell-ghc-mod settings. You can explicitly call check action from command palette 'Haskell IDE' menu (if you're using ide-haskell), or assign keybindings using Atom's keymap file. See https://github.com/atom-haskell/haskell-ghc-mod#keybindings

**Comment by trin-cz** [comment]
I see. Yes, by recompilation I meant parsing and type-checking. For some reason the "Settings" part of the haskell-ghc-mod package page was not being displayed. I see it now. Probably not fault of haskell-ghc-mod.
We can close this. Thank you.
