### ISSUE TITLE
Errors and Warnings do not show when the same file is open in two tabs

### ISSUE THREAD

**Issue by rgleichman** [atom-haskell/haskell-ghc-mod#118]
Here's a screenshot:
![atom_screenshot](https://cloud.githubusercontent.com/assets/1145705/13166936/87bbcdb8-d682-11e5-85c2-0ac7a9939980.png)

When the same file is open in multiple tabs (eg. by right clicking on the tab -> split right), the gutter error/warning triangles and corresponding text highlighting only displays for one of the tabs.

Clicking on the line numbers for the error (in this case `/home/robbie/git/robbie/glance/app/Translate.hs: 112, 47`) in the bottom panel still moves the cursor in both tabs.

Versions:
haskell-ghc-mod 1.6.6
ide-haskell 1.3.9
Atom 1.4.0
Ubuntu 14.04
Ghc Modi is enabled

**Comment by lierdakil** [comment]
Probably a problem with ide-haskell itself. I'll take a look when I'm able.

**Comment by rgleichman** [comment]
Thank you for fixing this. It now works for me with ide-haskell 1.5.2
