### ISSUE TITLE
No errors/warnings/lint are displayed

### ISSUE THREAD

**Issue by WillSewell** [atom-haskell/haskell-ghc-mod#121]
I have set up this package as described in the README. I'm using it for a stack project with versions:

* Atom: 1.5.3
* haskell-ghc-mod: 1.9.5
* ghc-mod: 5.5.0.0
* ghc: 7.10.3

I get types/info when I hover over identifiers in the source code, but I do not have any error/warning/lint messages showing up, even though I have "On Save Lint" and "On Save Check" set. When I look at the Console, I see the queries to `ghc-mod type` and `ghc-mod info`, but no queries to `ghc-mod check`.

Do you know what the problem is?

Thanks.

**Comment by WillSewell** [comment]
I just downgraded to v1.6.6 and it now works.

**Comment by lierdakil** [comment]
Does calling check from menu/command palette work? Do you have ide-haskell installed? What version? Lastly, *if* you're using ide-haskell frontend, make sure 'Use Linter' is disabled in haskell-ghc-mod settings, because it switches haskell-ghc-mod to use 'linter' package to display check results -- if you don't have it installed, it won't work.

**Comment by WillSewell** [comment]
Ah that was the problem. I didn't realise 'Use Linter' meant the `linter` package (which was not installed). Might be worth documenting that it won't work without this?

Thanks for a amazing plugin btw!

**Comment by lierdakil** [comment]
Well, option description does explicitly state 'Use Atom Linter service for check and lint'. Maybe it's not quite obvious what that implies... I could of course add a check for linter activation, but that comes with a whole lot of caveats in itself. I'll try rewording this description though.

**Comment by lierdakil** [comment]
Done. Also added a section explaining this to README. Hopefully, this leads to less confusion.

**Comment by WillSewell** [comment]
Thanks! That's a lot clearer.
