### ISSUE TITLE
Add additional file for the lint/hlint check

### ISSUE THREAD

**Issue by maroselo** [atom-haskell/haskell-ghc-mod#123]
Hi, I use haskell-IDE when working on my school project in Haskell. We were given the file (say Hlint.hs), that contains additional hints for the hlint. The instructions were to place it in the `~/.ghc` folder. This works when I run hlint from the Terminal. It's because, we were also given another file (ghci.conf) that contains the definition of the `ghci` command `:hlint` so it's pretty easy to execute hlint directly from the `ghci`. 
My question is whether it is possible to integrate the additional hint file (Hlint.hs) within the lint/hlint part of the IDE so that it could show me additional hints, that are setup in that file. 
Thanks for the response.

**Comment by lierdakil** [comment]
I think you can do something like this with `ghc-mod lint --hlintOpt --hint --hlintOpt /path/to/HLint.hs <file to lint>`. At the moment, there is no option to pass user arguments to ghc-mod though. I might be able to  make a quick patch for that though.

**Comment by lierdakil** [comment]
Okay, so there is `hlintOptions` setting in v1.10.0. You can specify comma-separated list of options that will be passed to hlint. DO NOT add `--hlintOpt`, it's done automatically.

F.ex., `--hint=/path/to/hint/file,--ignore=hint-to-ignore`.

Refer to `hlint --help` for available options.

**Comment by maroselo** [comment]
Well done! Thank you again, mate. I think you can close this issue now.
