### ISSUE TITLE
"stack exec atom" under Windows doesn't work

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#137]
According to this: https://github.com/atom-haskell/haskell-ghc-mod/wiki/Using-with-stack
"stack exec atom" should work. But it gives:

> C:\Users\Home\AppData\Local\atom\bin\atom: createProcess: invalid argument (Exec format error)

There is really such file, but it is only 1Kbytes in size.
Windows 10 x64

**Comment by lierdakil** [comment]
So I gather it doesn't work in 'regular mode', i.e. without `stack exec`? In most cases, it should.

As for `stack exec atom` itself, you just probably need to specify full path to atom executable. I have no idea where it's installed on your system, but you can probably figure that out.

F.ex.: `stack exec "C:\Program Files\Atom\atom.exe"`

**Comment by varosi** [comment]
Yes, it is not working in "regular mode". And it is not working using stack
like that:

stack exec "C:\Users\Home\AppData\Local\atom\app-1.7.3\atom.exe"

It is by default installed there on Windows 10.

2016-05-04 11:16 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
Then you'll have to explain what isn't working in more detail. It's probably unrelated to the whole `stack exec` thingy.

Also, what ghc-mod version do you use? 5.5.0.0 is strongly recommended. 5.4.0.0 also works somewhat. Earlier versions either don't support stack, or aren't supported by ide-haskell.

**Comment by varosi** [comment]
ghc-mod is 5.5.0.0

There is no problem to install other plug-ins in Atom.

What information do you need? I'll be glad to help with finding that. May
be it cannot find "coffee" compiler because of wrong environment variables?

2016-05-04 12:14 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by varosi** [comment]
"ide-haskell" plug-in is installing without problems. So it is something
related to "language-haskell" I think.

2016-05-04 17:16 GMT+03:00 eng. Vassil Ognyanov Keremidchiev <
varosi@gmail.com>:

**Comment by lierdakil** [comment]
Wait, what? I'm lost now. What are you talking about?

**Comment by lierdakil** [comment]
Oh. I see. https://github.com/atom-haskell/language-haskell/issues/73. I missed that.

**Comment by varosi** [comment]
Ops, my fault! I had written to wrong project. 

This issue here is for the documentation itself about Windows. 

stack exec "C:\Users\Home\AppData\Local\atom\app-1.7.3\atom.exe"

did run Atom editor, but I cannot test it without atom-haskell/language-haskell#73

**Comment by varosi** [comment]
> stack exec "%USERPROFILE%\AppData\Local\atom\app-1.7.3\atom.exe"

will work for all users

**Comment by lierdakil** [comment]
FYI, it's on wiki. So you should be able to edit it, I think.

**Comment by varosi** [comment]
Done!
