### ISSUE TITLE
Ask `stack` for common paths to ghc and ghc-mod

### ISSUE THREAD

**Issue by 3noch** [atom-haskell/haskell-ghc-mod#147]
When a project uses `stack`, it commonly uses the `ghc` and `ghc-mod` that are associated with the snapshot/resolver for that project. Ideally, this plugin would look for both of those in the snapshot folders before looking elsewhere:

`$(stack path --snapshot-install-root)/bin` tells you where the `ghc-mod` binary would be if the user ran `stack build ghc-mod cabal-helper`

`stack path --compiler-bin` tells you where the `ghc` binary is.

**Comment by lierdakil** [comment]
Stack 1.0 doesn't have `--compiler-bin` flag. In any case, it already does that.

**Comment by 3noch** [comment]
You could fall back to `stack exec which ghc`.

**Comment by 3noch** [comment]
I get an error that `ghc` could not be spawned.

**Comment by lierdakil** [comment]
Which version?

**Comment by 3noch** [comment]
Oh sweet. I see you just fixed that. I just upgraded to latest.

**Comment by 3noch** [comment]
Looks like ghc-mod is being pulled from the right place too!

**Comment by 3noch** [comment]
Thanks. Good work.
