### ISSUE TITLE
[Readme] Wrong links to services descriptions

### ISSUE THREAD

**Issue by rvion** [atom-haskell/haskell-ghc-mod#15]
The two links at the bottom of the readme (see picture below) give 404 error

![screen shot 2015-05-28 at 23 23 18](https://cloud.githubusercontent.com/assets/2150990/7872003/96ee9adc-0594-11e5-8777-f2a8407c594b.png)

**Comment by lierdakil** [comment]
Oh. Silly me. Hold on.

**Comment by lierdakil** [comment]
Fixed. Thanks.
