### ISSUE TITLE
Duplicate "Go To Declaration"

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#152]
Now there are two "Go to declaration" commands - one of Atom and one of ghd-mod sub-menu. 

It will be more less confusing if it is only one common command integrated with Atom's one.

This of course is very small issue.

**Comment by lierdakil** [comment]
There's a reason for this. Atom's go-to-decl is overriden by ide-haskell-hasktags. Ghc-mod's one is there for the sake of completeness, and it can give better results than hasktags one in some cases, but it's slower and lacks history (i.e. you can't automatically go 'back' once you've gone to declaration). Long story short, I just do both.

**Comment by varosi** [comment]
Thanks for the full answer!
