### ISSUE TITLE
Type information is not working for ./Setup.hs with Stack

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#156]
Cabal projects may have Setup.hs files in the folder where .cabal file reside. 
Currently it doesn't show type information for its contents on Windows. 

There are errors like:

> haskell-ghc-mod warning: EXCEPTION: browse:
>            Could not find module `Main'
>            Use -v to see a list of the files searched for.
> 
> util.coffee:36 haskell-ghc-mod warning: EXCEPTION: browse:
>            Could not find module `System.Process'
>            It is a member of the hidden package`process-1.2.3.0'.
>            Perhaps you need to add `process' to the build-depends in your .cabal file.
>            Use -v to see a list of the files searched for.
> 
> util.coffee:36 haskell-ghc-mod warning: EXCEPTION: browse:
>            Could not find module `System.FilePath'
>            It is a member of the hidden package`filepath-1.4.0.0'.
>            Perhaps you need to add `filepath' to the build-depends in your .cabal file.
>            Use -v to see a list of the files searched for.

**Comment by lierdakil** [comment]
Setup.hs is not part of cabal project, but ghc-mod assumes it is. I suggest
you file an issue on ghc-mod repo.
6 июня 2016 г. 4:19 PM пользователь "varosi" <notifications@github.com>
написал:

**Comment by lierdakil** [comment]
That said, you could add dependencies to cabal file.
6 июня 2016 г. 4:23 PM пользователь "Nikolay Yakimov" <root@livid.pp.ru>
написал:
