### ISSUE TITLE
go-to definition opens non existent file

### ISSUE THREAD

**Issue by bblfish** [atom-haskell/haskell-ghc-mod#158]
I have succeded in getting most things to work using dalaing's cofun project:
 https://github.com/dalaing/cofun

most importantly if I leave my mouse over a definition I can see the code definition. Here is an example where it shows me the definition that is just a few lines up higher.

![screenshot 2016-06-14 18 07 14](https://cloud.githubusercontent.com/assets/124506/16050181/f88e3ca4-325a-11e6-82b9-4b101ce7a08f.png)

But if I use the goto to definition it will open a new file at the wrong relative URL, so it won't jump to the definition but to an empty file.

**Comment by lierdakil** [comment]
It might help if you specify how the relative url is "wrong" exactly.
Thanks.

2016-06-14 19:10 GMT+03:00 Henry Story <notifications@github.com>:

**Comment by bblfish** [comment]
yes. The file that is opened is `/Volumes/Dev/Programming/Haskell/cofun/code/src/AdderService/Adder/Interpreter/Transformer.hs`
whereas the file that should be opened is
`/Volumes/Dev/Programming/Haskell/cofun/code/adder/src/AdderService/Adder/Interpreter/Transformer.hs`
The root directory that contains all the projects is on my file system:
`/Volumes/Dev/Programming/Haskell/cofun/code/`

**Comment by lierdakil** [comment]
v1.14.6 should hopefully fix this. If not, let me know.

2016-06-15 12:37 GMT+03:00 Henry Story <notifications@github.com>:

**Comment by bblfish** [comment]
yep that works now thanks!
