### ISSUE TITLE
Proposition: Remove duplicated first line (short type info) in ghd-mod hints

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#169]
![atom1](https://cloud.githubusercontent.com/assets/6051718/17854228/cc926c4c-6879-11e6-93c1-40daafb5b532.png)

As I understand first line is short type info and second, third, etc are description. My proposition is if "short description" is literally contained inside "full type information" to remove it (first line), so only full description is left. This will minimize type information clutter and will normalize information inside it a bit.

**Comment by lierdakil** [comment]
I understand where you're coming from, but there are two reasons for having it this way:

- Fixing this would introduce unnecessary complexity into code that's complex enough as it is
- There are cases where getting type might not work, while getting full info works fine. It's useful to be able to differentiate at a glance if it's that. Hiding instantiated type will make this nigh impossible.

**Comment by varosi** [comment]
For the second point - it could be enabled in Debug mode to visualize both. But in normal non-debug to remove duplicate. By removing duplicate, I mean just search for first line in full text information literally - infix search. Not more complex than that.

**Comment by lierdakil** [comment]
Implemented in v2.2.1

**Comment by varosi** [comment]
Works great! Thanks a lot!
