### ISSUE TITLE
Missing icons on plug-ins during update screen

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#171]
![atom1](https://cloud.githubusercontent.com/assets/6051718/17981763/afa13e6a-6b0d-11e6-9ec1-5c6f683f8823.png)

I'm behind a proxy here, but updates are working fine.

**Comment by lierdakil** [comment]
That's definitely not a problem with packages. Either github, your internet connection or Atom itself are at fault.
