### ISSUE TITLE
ghc-mod using all my memory

### ISSUE THREAD

**Issue by BillyBadBoy** [atom-haskell/haskell-ghc-mod#178]
I've re-installed atom on a new linux installation and find that I can only work with atom for half an hour or so before it grinds to a halt. When I do a 'top' from a terminal I see that the ghc-mod process is using about 80% of my memory - which never gets released. I have always had atom configured to check and lint on any change and have never had this problem before. 

As a workaround I am only checking/linting on save. This lets me work for much longer - but even like this the memory usage for ghc-mod slowly creeps upwards.

Any ideas ?

**Comment by lierdakil** [comment]
See https://github.com/DanielG/ghc-mod/issues/834 -- it's *probably* related to that. TL;DR this is mostly apparent with ghc-8, due to overall higher memory consumption.
