### ISSUE TITLE
Syntax coloring of hints is some kind broken from third line below

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#180]
![image](https://cloud.githubusercontent.com/assets/6051718/19052783/cd977eb2-89c0-11e6-8122-9b280733df03.png)

"instance" word doesn't have correct coloring after second line.
Atom 1.10.02
Windows 8.1 x64
latest atom-haskell plug-ins

**Comment by lierdakil** [comment]
I believe this was fixed along the line somewhere. Let me know if not.

**Comment by varosi** [comment]
Yes, indeed! On latest version of plug-ins and Atom it works just fine! Thanks a lot!
