### ISSUE TITLE
How to add key mapping of type insert?

### ISSUE THREAD

**Issue by li-zhirui** [atom-haskell/haskell-ghc-mod#183]
I want to map `ctrl-p` and `ctrl-n` for up and down thought the list only when the content list of `insert-type` and `go-to-declaration` shows. Is there any way I can do that?

I can't add it as a global key mapping, because I map `ctrl-p` as the toggle key of fuzzy finder. That means I want to map the key as:

```cson
'.platform-win32 atom-text-editor.autocomplete-active':
  'ctrl-p': 'autocomplete-plus:move-up'
  'ctrl-n': 'autocomplete-plus:move-down'

'.platform-win32 atom-text-editor.<??? something like "haskell-ghc-mod.insert-type">':
  'ctrl-p': 'core:move-up'   <---- or something like 'haskell-ghc-mod:move-up'
  'ctrl-n': 'core:move-down'

'atom-text-editor':
  'ctrl-p': 'fuzzy-finder:toggle-file-finder'
```

Thanks!

**Comment by lierdakil** [comment]
Something like this should do the trick:

```cson
"atom-workspace .select-list.ide-haskell":
  "ctrl-p": "core:move-up"
```

More specific targeting isn't possible at the moment,  though, i.e. all ide-haskell-related select lists will have those bindings. I don't really think it's a problem, but you're free to try to convince me otherwise.

**Comment by li-zhirui** [comment]
That works fine! Thanks very much @lierdakil : )
