### ISSUE TITLE
lint options

### ISSUE THREAD

**Issue by BillyBadBoy** [atom-haskell/haskell-ghc-mod#185]
This is a question not a bug report. I'm trying to get atom to ignore `Use string` warnings, but I can't figure it out. I've tried this pragma in my module: `{-# ANN module "HLint: ignore Use string literal" #-}` - but it had no effect.

Is there an hlint option that will work ?

**Comment by lierdakil** [comment]
Um. Did you mean `{-# ANN module "HLint: ignore Use String" #-}`? "Use string literal" was disabled about a year ago in https://github.com/ndmitchell/hlint/commit/f78664477cb84573eb7ce7d72d37d9236c76073e

**Comment by BillyBadBoy** [comment]
You're right - I am now warning free !!
Thnx
