### ISSUE TITLE
Can't find cabal_helper_libexecdir

### ISSUE THREAD

**Issue by turtle11311** [atom-haskell/haskell-ghc-mod#188]
I add $cabal_helper_libexecdir to my bashrc, it can run ghc-mod in command line, but in atom still error with cabal_helper_libexecdir
```
ghc-mod: ghc-mod: Could not find $libexecdir/cabal-helper-wrapper-v0.7
If you are a developer set the environment variable
`cabal_helper_libexecdir' to override $libexecdir[1]. The following will
work in the cabal-helper source tree:
    $ export cabal_helper_libexecdir=$PWD/dist/build/cabal-helper-wrapper-v0.7
[1]: /usr/lib
If you don't know what I'm talking about something went wrong with your
installation. Please report this problem here:
    https://github.com/DanielG/cabal-helper/issues
```

**Comment by lierdakil** [comment]
Try setting it in Atom init script, e.g.

process.env.cabal_helper_libexecdir = '/path/to/libexecdir'

Although technically, this path should be baked-in if you installed

2016-11-05 7:50 GMT+03:00 Wong, Fu-Lian <notifications@github.com>:

**Comment by lierdakil** [comment]
... ghc-mod correctly.

2016-11-05 8:48 GMT+03:00 Nikolay Yakimov <root@livid.pp.ru>:

**Comment by turtle11311** [comment]
thanks it work
