### ISSUE TITLE
Deprecated selector in `haskell-ghc-mod/styles/linter.atom-text-editor.less`

### ISSUE THREAD

**Issue by clojj** [atom-haskell/haskell-ghc-mod#191]
In `haskell-ghc-mod/styles/linter.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host[data-grammar~='haskell'] .linter-highlight.lint,
.linter-highlight.lint` => `atom-text-editor[data-grammar~='haskell'] .linter-highlight.lint,
.linter-highlight.lint`

* `:host[data-grammar~='haskell'] .linter-highlight.lint:not(.line-number),
.linter-highlight.lint:not(.line-number)` => `atom-text-editor[data-grammar~='haskell'] .linter-highlight.lint:not(.line-number),
.linter-highlight.lint:not(.line-number)`

* `:host[data-grammar~='haskell'] .linter-highlight.lint .icon-right::before,
.linter-highlight.lint .icon-right::before,
:host[data-grammar~='haskell'] .linter-highlight.lint .linter-gutter,
.linter-highlight.lint .linter-gutter` => `atom-text-editor[data-grammar~='haskell'] .linter-highlight.lint .icon-right::before,
.linter-highlight.lint .icon-right::before,atom-text-editor[data-grammar~='haskell'] .linter-highlight.lint .linter-gutter,
.linter-highlight.lint .linter-gutter`

* `:host[data-grammar~='haskell'] .linter-highlight.lint .region,
.linter-highlight.lint .region` => `atom-text-editor[data-grammar~='haskell'] .linter-highlight.lint .region,
.linter-highlight.lint .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lierdakil** [comment]
Will try to release a new version soon. Relevant patches are already in
atom-1.13 branch.

чт, 12 янв. 2017 г., 2:12 clojj <notifications@github.com>:

**Comment by lierdakil** [comment]
All should be good now.
