### ISSUE TITLE
Haddock documentation view at the top of type info hints

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#193]
It'll be very useful if there is a way to show Haddock documentation for the given symbol on top of type info hints. I don't know how this could be done. May be using directly Haddock or via Hoogle?

**Comment by varosi** [comment]
I found related issue in other project: https://github.com/atom-haskell/ide-haskell/issues/169
So I think this is duplicate.

**Comment by varosi** [comment]
I mean at least function comments to be visible in hints.

**Comment by lierdakil** [comment]
You mean docstrings? Those can be a screen long.

**Comment by varosi** [comment]
I mean if a function is defined like that:

```
-- | My documentation
myFunc :: Int -> Int
```

To see "My documentation" inside hints. If it's too long - it could be truncated to 3-4 lines.
