### ISSUE TITLE
lint fails with: Invalid option `--hlintOpt'

### ISSUE THREAD

**Issue by lippling** [atom-haskell/haskell-ghc-mod#198]
When I use HLint options like `-XNoRoleAnnotations` the plugin doesn't work anymore. For example:

```
ghc-mod lint server/Settings/StaticFiles.hs -- --hlintOpt -XNoRoleAnnotations 
```
results in
```
Invalid option `--hlintOpt'
```

The problem is the `--`. Removing them by hand works:
```
ghc-mod lint server/Settings/StaticFiles.hs --hlintOpt -XNoRoleAnnotations
```
but the plugin adds `--` automatically.

Could this be fixed easily?

**Comment by eatobin** [comment]
I have the same problem.

**Comment by lierdakil** [comment]
Thanks for reporting, should be fixed in the latest version. Please let me know if not (although I did test and am pretty sure everything should be fine)
@eatobin, bear in mind some hlint options are ignored by ghc-mod v5.6 and v5.7 -- this is mostly a problem with hlint's API, and `master` switched to *other* hlint API, which works fine, but that hasn't been released as of yet. v5.5 is fine (but it uses older hlint)

**Comment by eatobin** [comment]
Thanks @lierdakil for the reply. This does work for me from the command line:

```
eric@linux-epth:total-beginner-haskell$ ghc-mod lint -h '--hint=Default.hs' -h '--hint=Dollar.hs' -h '--hint=Generalise.hs' src/Borrower.hs
src/Borrower.hs:44:3: Suggestion: Use mappendFound:  getName br ++    " (" `mappend` show (getMaxBooks br) `mappend` " books)"Why not:  getName br `Data.Monoid.mappend`    (" (" `mappend` show (getMaxBooks br) `mappend` " books)")
```

I'm using ghc-mod 5.6 built from Github.

Maybe I'm just entering the arguments wrong in Atom. Can you show me what the entry should be in Atom for the arguments above?

Thank you.

**Comment by lierdakil** [comment]
@eatobin, something like this should be equivalent to your command line:
![image](https://cloud.githubusercontent.com/assets/7275622/23049159/6659024a-f4cb-11e6-8634-aa3e575c7d17.png)
Note you need hgm v1.19.7 for this to work, which was released half an hour ago, so check for updates. Sorry if it wasn't clear.

**Comment by eatobin** [comment]
Works fine @lierdakil. Thank you for your help!

**Comment by lippling** [comment]
That was quick. Thanks!
