### ISSUE TITLE
Atom 1.15.0 + haskell-ghc-mod 1.19.7 = no type info on mouseover

### ISSUE THREAD

**Issue by ThomasLocke** [atom-haskell/haskell-ghc-mod#207]
It works with Atom 1.14.3 and haskell-ghc-mod 1.19.7, so there seems to be something going on somewhere between 1.14.3 and 1.15.0

The console outputs the following on mouseover:

```
haskell-ghc-mod warning: ghc-modi said: EXCEPTION: types: attempting to use module ‘Main’ (src/Main.hs) which is not loaded
util.coffee [sm]:36 haskell-ghc-mod warning: ghc-modi said: EXCEPTION: info:
util.coffee [sm]:36 haskell-ghc-mod warning: ghc-modi said:                attempting to use module ‘Main’ (src/Main.hs) which is not loaded
upi.coffee:157 Error: Got neither type nor info(…)
```

**Comment by ThomasLocke** [comment]
Console log after enabling the debug flag in haskell-ghc-mod:

https://gist.github.com/ThomasLocke/afc7037dd4d944b26705de235fe4cf1b

**Comment by lierdakil** [comment]
Okay... and what happens if you run `ghc-mod type /home/thomas/vcs/darcs/passgen/src/Main.hs -c -- 27 4` in `/home/thomas/vcs/darcs/passgen`?

**Comment by lierdakil** [comment]
Run from shell I mean.

**Comment by ThomasLocke** [comment]
@lierdakil it fails. Miserably.

EXCEPTION: types: attempting to use module ‘Main’ (src/Main.hs) which is not loaded

So some sort of problem on my end. Closing issue. Sorry for the bother.
