### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by etorreborre** [atom-haskell/haskell-ghc-mod#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.6.6

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of null

```
At /Users/etorreborre/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:87

TypeError: Cannot read property 'dispose' of null
    at ModuleInfo.destroy (/Users/etorreborre/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:140:23)
    at /Users/etorreborre/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:3:61
```

### Commands

```
  2x -2:03.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:59.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:59.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:57.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:57.3.0 core:move-right (atom-text-editor.editor.is-focused)
 11x -1:56.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:54.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.9.0 core:undo (atom-text-editor.editor.is-focused)
     -1:28.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  6x -1:27.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:25.4.0 core:paste (atom-text-editor.editor.is-focused)
     -1:24.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:24.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  6x -1:23.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:21.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModPath": "/Users/etorreborre/projects/haskell/ghc-mod/.cabal-sandbox/bin/ghc-mod",
    "ghcModiPath": "/Users/etorreborre/projects/haskell/ghc-mod/.cabal-sandbox/bin/ghc-modi",
    "disableFrontend": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.3
haskell-ghc-mod, v0.6.6
ide-haskell, v0.5.8
language-haskell, v1.0.0
language-scala, v1.1.2
linter-hlint, v0.3.6

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I'm publishing 0.7.0, which should hopefully help with this. Feel free to reopen if this persists in some form.

**Comment by etorreborre** [comment]
Thanks a lot by the way, the environment sees to be working ok for me now, including tooltips and all.

The only thing is that the errors panels is sometimes complaining about having some modules not found until I press save for the second time (even if the module in question is not brand new).

**Comment by lierdakil** [comment]
@etorreborre, thanks for using ide-haskell!

On the topic of your problem with modules, please consider filing a new issue with a more detailed description of what goes wrong for you. I can't say I ever encountered behavior you are describing, and at the moment I have no idea what could be causing it, but I would be happy to rectify it, if possible.

I try to aim for "go-to" IDE for Haskell, and little bugs like that could deter people from using it, so your report would help a great deal.

**Comment by etorreborre** [comment]
Ok I'll try to see if we have a public project where I can reproduce the issue. One thing I noticed tonight is that the plugin, on OSX, seems to better behave when launched from a terminal. Otherwise I got some messages like `readProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`. A [bit of googling](https://github.com/Atsky/haskell-idea-plugin/issues/50) gave me that workaround.

**Comment by etorreborre** [comment]
I create issue #22 for the `Could not find module` issue.

**Comment by lierdakil** [comment]
It was a known problem with Atom on OSX, but I was under the impression it was fixed along the road. Apparently not. Sadly, I don't have access to OSX, so I can't test there. I will try to provide some method of adding specific directories to PATH and update documentation accordingly, thanks for bringing this to my attention.

And thanks for opening the issue.
