### ISSUE TITLE
ghc-mod consumes too much memory

### ISSUE THREAD

**Issue by welf** [atom-haskell/haskell-ghc-mod#210]
`ghc-mod` consumes too much memory (macOS Sierra 10.12.4) when working with *.hs files of decent size (only 102 lines). I need regulary free RAM or relaunch Atom. 
<img width="797" alt="ghc-mod" src="https://cloud.githubusercontent.com/assets/1454462/25413744/f22073c6-2a2c-11e7-87f0-dcfebb14b3d9.png">

**Comment by lierdakil** [comment]
Known issue with GHC 8.0.1 at least. Can't do much on my end. See https://github.com/DanielG/ghc-mod/issues/834

**Comment by welf** [comment]
It's a problem with GHC 8.0.2 too because I use it.

**Comment by lierdakil** [comment]
Somewhat solved in recent versions that try to restart ghc-mod if it eats too much RAM (configurable). Obviously a band-aid, but that's all I can do here.
