### ISSUE TITLE
suppress linter suggestions

### ISSUE THREAD

**Issue by nineonine** [atom-haskell/haskell-ghc-mod#216]
Sometimes linter makes suggestions that I am not interested in and want to keep my code as is. Would it be possible to somehow suppress particular suggestions but still keep linter enabled?

**Comment by lierdakil** [comment]
See [hlint manual on the topic](https://github.com/ndmitchell/hlint#customizing-the-hints).

I should note that particularities depend heavily on hlint version, and IIRC there were some bugs in ghc-mod that interfered with the ignore mechanism (DanielG/ghc-mod#800, DanielG/ghc-mod#826), so be aware of that.

**Comment by nineonine** [comment]
alright, hlint ignore annotations worked pretty well for me. Thanks!
