### ISSUE TITLE
cabal install ghc-mod error

### ISSUE THREAD

**Issue by leon1995** [atom-haskell/haskell-ghc-mod#227]
Hi.

I´m trying to install ghc-mod from cabal on Win10 64Bit but I get this error

`PS C:\Users\LeonWin10> cabal install ghc-mod
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
trying: ghc-mod-5.8.0.0 (user goal)
next goal: base (dependency of ghc-mod-5.8.0.0)
rejecting: base-4.10.0.0/installed-4.1... (conflict: ghc-mod => base<4.10 && >=4.6.0.1)
rejecting: base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, ghc-mod, syb`

It would be great, if someone has a solution :)

**Comment by leon1995** [comment]
solved it by using stack. Please close this

**Comment by lierdakil** [comment]
Looks like you have GHC 8.2. ghc-mod doesn't support it yet, hence the error. Stack is still on GHC 8.0 by default, so that works out.

Closing per your request.
