### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by Magnificus36** [atom-haskell/haskell-ghc-mod#23]
Yesterday it worked. Today I updated the ide-haskell and haskell-ghc-mod plugins.

Step to reproduce:
Simply reopening Atom with some haskell files open. Or simply opening a haskell file.

Together with the uncaught error message I also get the message: "'ghc-modi' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."
I checked and ghc-modi is in my path.

**Atom Version**: 0.207.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.7.1

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at exports._errnoException (util.js:734:11)
    at Socket._writeGeneric (net.js:668:26)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at GhcModiProcessTemp.module.exports.GhcModiProcessTemp.runModiCmd (C:\Users\Student\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process-temp.coffee:148:28)
    at GhcModiProcessTemp.runModiCmd (C:\Users\Student\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process-temp.coffee:3:61)
    at GhcModiProcessTemp.module.exports.GhcModiProcessTemp.run (C:\Users\Student\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process-temp.coffee:60:23)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.3
haskell-ghc-mod, v0.7.1
ide-haskell, v0.5.9
language-haskell, v1.0.0
language-prolog, v0.9.0
run-in-terminal, v0.2.2

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Thank you for reporting this.

If I had to guess, maybe latest changes to PATH handling botched it on Windows.

Could you check something? Add some path (`C:\` for example) to additionalPathDirectories configuration option, something like shown below, and restart Atom.

![image](https://cloud.githubusercontent.com/assets/7275622/8015990/8d31e5d2-0be6-11e5-9bc4-d7c93ad7393f.png)

If it helps, I'll know what to change. If it doesn't, we'll need to investigate further.

**Comment by Magnificus36** [comment]
WIth just 'C:\' it still does not work.
For now I have put the full path of the directory with ghc-mod(i) there. And that seems to work.

(P.S. 've updated ide-haskell and haskell-ghc-mod to 0.5.10 and 0.7.3, which did not influence this issue)

**Comment by lierdakil** [comment]
Hmm. Could you enable `Debug` option in haskell-ghc-mod and check developer console for messages like `haskell-ghc-mod debug: PATH = ...` to check if it picks up your system PATH?

**Comment by Magnificus36** [comment]
I see: haskell-ghc-mod debug: PATH = C:\Users\Student\Documents\Module 8\practicum\functional-programming\project/.cabal-sandbox/bin;C:\Users\Student\AppData\Roaming\cabal\bin\;undefined

"C:\Users\Student\Documents\Module 8\practicum\functional-programming\project" is the 'project' folder I have open in Atom.

(In developer console I also checked to see what the value of 'process.env.path' is and that does have the correct values)

**Comment by lierdakil** [comment]
I'm sorry, but shouldn't `path` be capitalized (i.e. be `PATH`)? Most Windows administration guides I've seen use capitalized version. Sorry, not a Windows user, so I'm not sure on this one. If it's always lowercase, then this is an easy fix. If not, then this poses a slight problem...

**Comment by Magnificus36** [comment]
In my Windows Environment Variables I have the user specific variable PATH (which contains the cabal bin folder in my AppData) and a system wide variable Path which contains a most other directories. 

And when you query %PATH% in cmd you get a concatenation of system variable and user variable (of the currently logged in user).
In Atom the process.env.Path contains this same concatenation. (So in Atom it is for me process.env.Path however process.env.PATH and process.env.path also seem to work in de Atom developer console.)

**Comment by lierdakil** [comment]
So, let me get this straight. `process.env.PATH`, `process.env.Path` and `process.env.path` return the same thing on Windows?

**Comment by Magnificus36** [comment]
In the Atom developer console they to indeed.
The intellisense / auto-complete only suggests Path, however it looks like any random capitalisation of path works.

**Comment by lierdakil** [comment]
Okay, at least I *think* I know how to fix this. I just published v0.7.4. Could you check if it works for you?

**Comment by Magnificus36** [comment]
Thanks! This seems to work.
On console I now see a debug message containing my complete path.

**Comment by lierdakil** [comment]
Please check if it *actually* works, i.e. if it finds `ghc-mod[i]`. I'm a little bit unsure on this one.

**Comment by Magnificus36** [comment]
It looks like everything is working. (With the Additional Path Directories cleared)

**Comment by lierdakil** [comment]
Great! Thanks for your help with squaring this out!
