### ISSUE TITLE
Hovering over function parameter name gives exception

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#236]
If you hover over function parameter name *Ghc-mod* windows is shown with exception:

> EXCEPTION: info:     Not in scEXCEPTION: info:     Not in scope: `success'EXCEPTION: info:     Not in scope: `bank'

but after a second or so a tooltip show type information. So basically it's working, but this window pop-up each time is annoying and takes screen space (which is precious on a laptop display).

**Comment by varosi** [comment]
It's similar for imports with exception:

> EXCEPTION: info:     Not in scope: `Persist'

In my opinion for type information hints it's better not to pop-up such windows, i.e. to hide such errors and provide them to the user only if she's willing to check them somewhere.

**Comment by varosi** [comment]
Sorry, I found a way to suppress it. There is a setting for that to show error messages only in development console. 
So may be this issue could be turned out so this to be default option?

**Comment by lierdakil** [comment]
Uh... it *is* the default.
https://github.com/atom-haskell/haskell-ghc-mod/blob/5921c5a89b309e0f3f5c56580084d96be90ac55d/src/config.ts#L192-L202

**Comment by varosi** [comment]
Thanks! Sorry! May be only my settings was altered.
