### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by itkovian** [atom-haskell/haskell-ghc-mod#24]
[Enter steps to reproduce below:]

1. Open a haskell file (in particular, Course/List.hs from https://github.com/NICTA/course

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.4
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.7.4

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of null

```
At /Users/ageorges/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:38

TypeError: Cannot read property 'get' of null
  at GhcModiProcessTemp.module.exports.GhcModiProcessBase.killProcessForDir (/Users/ageorges/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:38:5)
  at GhcModiProcessTemp.killProcessForDir (/Users/ageorges/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:1:1)
  at /Users/ageorges/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:15:29

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pyflakes",
      "linter-shellcheck",
      "language-haskell",
      "autocomplete-haskell"
    ],
    "destroyEmptyPanes": false
  },
  "haskell-ghc-mod": {
    "ghcModiPath": "/Users/ageorges/Library/Haskell/bin/ghc-modi",
    "ghcModPath": "/Users/ageorges/Library/Haskell/bin/ghc-mod"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus-python-jedi, v0.3.6
haskell-ghc-mod, v0.7.4
ide-haskell, v0.5.10
linter, v0.12.6
linter-flake8, v1.4.2
linter-hlint, v0.3.6
linter-pep8, v0.2.0
minimap, v4.9.4
project-manager, v1.15.10
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I've published 0.7.5, which should help with error message itself, but please bear in mind that you should launch Atom with project directory (one containing `*.cabal`, e.g. `atom /path/to/project`). If you open individual files, it opens in directory containing file, which can mess up project settings detection, and, in general, won't work as expected.

**Comment by itkovian** [comment]
I ran ```atom .``` in the project dir, so it has a cabal file etc.

**Comment by lierdakil** [comment]
That's weird. Anyway, does 0.7.5 work for you, or do we need to research this further?

**Comment by itkovian** [comment]
Seems to work, thx!

**Comment by jbracker** [comment]
I just got this error message out of the blue while working in a project:

~~~
Uncaught TypeError: Cannot read property 'getUri' of null
/home/jbracker/.atom/packages/haskell-ghc-mod/lib/util.coffee:14
Hide Stack Trace
TypeError: Cannot read property 'getUri' of null
  at /home/jbracker/.atom/packages/haskell-ghc-mod/lib/util.coffee:14:26
  at Array.filter (native)
  at Object.module.exports.Util.getRootDir (/home/jbracker/.atom/packages/haskell-ghc-mod/lib/util.coffee:13:43)
  at CompletionBackend.module.exports.CompletionBackend.getModuleMap (/home/jbracker/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:59:21)
  at CompletionBackend.getModuleMap (/home/jbracker/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:1:1)
  at CompletionBackend.module.exports.CompletionBackend.getSymbolsForBuffer (/home/jbracker/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:35:29)
  at CompletionBackend.getSymbolsForBuffer (/home/jbracker/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:1:1)
  at /home/jbracker/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:313:10
  at queueCmd.callback (/home/jbracker/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:166:9)
  at /home/jbracker/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:104:7
~~~

Atom Version: 1.0
System: Ubuntu Trusty 14.04
Thrown From: haskell-ghc-mod package v0.8.2

Afterwards types were not shown anymore. I do not know how to reproduce the error. If it comes up again, I will report it.

### Config

~~~
"*":
  editor:
    showIndentGuide: true
    invisibles: {}
    scrollPastEnd: true
    fontSize: 12
  core:
    themes: [
      "atom-dark-ui"
      "atom-light-syntax"
    ]
    disabledPackages: [
      "bookmarks"
    ]
  "ide-haskell":
    stylishHaskellPath: "/usr/local/bin/stylish-haskell"
    ghcModPath: "/usr/local/bin/ghc-mod"
  welcome:
    showOnStartup: false
  "autocomplete-plus": {}
  "haskell-ghc-mod": {}
  "git-diff":
    showIconsInEditorGutter: true
  minimap:
    plugins:
      selection: true
      linter: true
~~~

### Installed Community Packages

* autocomplete-haskell v0.4.5
* haskell-ghc-mod v0.8.2
* ide-haskell v0.6.2
* language-haskell v1.1.8
* minimap v4.10.2
* minimap-selection v4.3.0

**Comment by lierdakil** [comment]
@jbracker, from stack trace, it appears that you were trying to show completions for "hole" `_`. Is that correct?

**Comment by jbracker** [comment]
I'm sorry, but I don't know. I can't reproduce the error.

**Comment by lierdakil** [comment]
I think I know why this happened (some relatively rare conditions could lead to deleted buffer being re-used). I tried to simplify disposal logic a little bit, and hopefully, 0.8.3 won't have this error pop up anymore. Thanks for reporting!
