### ISSUE TITLE
Not Auto-completing Haskell properly

### ISSUE THREAD

**Issue by senthilporunan** [atom-haskell/haskell-ghc-mod#27]
Hi, 

I have installed 

$apm install language-haskell haskell-ghc-mod ide-haskell autocomplete-haskell

but, when i type import System. it is not auto-completing whole path. In Console, i am getting an error like : 

"haskell-ghc-mod debug: System. moduleName mismatch: undefined != System."

i have set haskell environmnet variables in PATH. I have set ghc-mod and ghc-modi as 
C:\Users\<username>\AppData\Roaming\cabal\bin

Let me know is there any configuration i missed to setup.

Thanks,
Senthil.

**Comment by lierdakil** [comment]
`undefined != something` is just a debug message meaning that you didn't specify module name for current file. That's perfectly normal. Debug messages are like that.

On the topic of `System.`, there is a known quirk with autocomplete-plus in that it doesn't consider dot `.` a valid completion symbol. Try autocompleting just `System`, or `System.I` for example.

**Comment by lierdakil** [comment]
Oopsie. Nope, I'm wrong, this was fixed a long time ago, but I didn't update accordingly. I'll try to fix this.

**Comment by lierdakil** [comment]
Okay, `language-haskell` v1.1.2 should allow autocompleting module names ending with dot. Thanks for reporting!

**Comment by senthilporunan** [comment]
Hi,

Still, facing the same issue. Now, i am using v1.1.4 version. Am i missing any configurational setup ? 

Thanks in advance.

**Comment by lierdakil** [comment]
First, autocompletion takes a little while to fire up, since it has to traverse modules for symbols.

Second, please describe what works and what doesn't. Does autocompletion work at all? Anywhere?

**Comment by senthilporunan** [comment]
for me, if i type "imp" import statment is pre-populating

second, if i type "import Da"  i am expecting import Data should come. But, it is not coming. 

third, if i type "import Data." i am expecting import Data.Char should come. But, it is not coming.

If i type "let" and enter "let
	name = expression
	in expression" 

Looks like, it is not working for module names.

**Comment by lierdakil** [comment]
Is `C:\Users\<username>\AppData\Roaming\cabal\bin` in PATH?

**Comment by lierdakil** [comment]
Or did you specify full path to `ghc-mod` and `ghc-modi` in `haskell-ghc-mod` settings?

**Comment by senthilporunan** [comment]
I had set ghc-mod : C:\Users\sporunan\AppData\Roaming\cabal\bin
ghc-modi: C:\Users\sporunan\AppData\Roaming\cabal\bin

in haskell-ghc-mod package.

**Comment by lierdakil** [comment]
You need to specify path to executable. In your case that would be something along the lines of
`C:\Users\sporunan\AppData\Roaming\cabal\bin\ghc-mod.exe`
and
`C:\Users\sporunan\AppData\Roaming\cabal\bin\ghc-modi.exe`

**Comment by senthilporunan** [comment]
Now, i had set ghc-mod: C:\Users\sporunan\AppData\Roaming\cabal\bin\ghc-mod.exe

ghc-modi: C:\Users\sporunan\AppData\Roaming\cabal\bin\ghc-modi.exe 

But still, if i type "import Data." i am expecting import Data.Char should come. But, it is not coming.

**Comment by senthilporunan** [comment]
I have installed autocomplete-haskell, haskell-ghc-mod, helium, ide-haskell, language-haskell.

**Comment by lierdakil** [comment]
You really should remove helium. I have no idea how it would interact with everything else.

**Comment by lierdakil** [comment]
What version of Atom are you using by the way?

**Comment by senthilporunan** [comment]
I am using atom version no: 0.209.0. I have removed helium package.  Now, its working now. 

Thanks a lot.

**Comment by lierdakil** [comment]
Good.
