### ISSUE TITLE
Typo in code?

### ISSUE THREAD

**Issue by ranjitjhala** [atom-haskell/haskell-ghc-mod#28]
Hi, I was just reading the code to understand how to write an hdevtools backend. Shouldn't this line:

https://github.com/atom-haskell/haskell-ghc-mod/blob/master/lib/haskell-ghc-mod.coffee#L41

say 

    unless atom.config.get('haskell-ghc-mod.suppressStartupWarning')

that is `gch` ====> `ghc` ?

Thanks!

Ranjit.

**Comment by lierdakil** [comment]
Yep, that's a typo. Thanks.

**Comment by lierdakil** [comment]
Fixed in 0.7.8.
