### ISSUE TITLE
Failed to spawn command ghc-mod

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/haskell-ghc-mod#29]
The latest update (not 100% sure about that) seems to have broken something.
It works for cabal projects, but when I open a single Haskell file I get the error.

Not really sure what other info I can provide.
I'm running Windows 8. Both Atom and all the ide-haskell packages are at their current latest versions.

This is the exception in the dev tools

```
Uncaught BufferedProcessError: Failed to spawn command `ghc-mod`. Make sure `ghc-mod` is installed and on your PATH
```

**Comment by lierdakil** [comment]
I'm sorry about that, but I won't be able to work on  this for a while due
to health  issues. I will gladly merge  a  PR though.
19 июня 2015 г. 20:16 пользователь "Luka Horvat" <notifications@github.com>
написал:

**Comment by LukaHorvat** [comment]
No problem. I'll see what I can do.

**Comment by lierdakil** [comment]
Please check if this problem persists with v0.7.9 (i think I might have fixed it)

**Comment by LukaHorvat** [comment]
Seems to work! Awesome!

**Comment by kaizhang** [comment]
I still have the same problem with 0.7.10. I use Atom 1.0

**Comment by lierdakil** [comment]
@kaizhang, please open a new issue with detailed description of your setup (ghc, ghc-mod versions, paths, package settings, etc) and what goes wrong. I think it might be unrelated. In any case, I can't reproduce this anymore, so I need more info.

**Comment by kaizhang** [comment]
I found it's working only if I open Atom with "sudo". Could you shed some light on this? @lierdakil

**Comment by lierdakil** [comment]
@kaizhang, well that suggests a permissions or PATH issue.

Try running Atom from terminal (without `sudo`), changing execution permissions on `ghc-mod` and `ghc-modi`, or configuring haskell-ghc-mod with `additonalPathDirectories` or specifying full path to `ghc-mod`/`ghc-modi`.

**Comment by kaizhang** [comment]
@lierdakil Running Atom from terminal without sudo won't work. I have tried everything including using full path, setting additional path, chmod 777 ghc-mod, etc.It's very weird.

**Comment by lierdakil** [comment]
I've published 0.7.11, which should at least output more verbose error
messages. Please try it, and check dev console for insight.

2015-06-28 21:51 GMT+03:00 Kai Zhang <notifications@github.com>:

**Comment by kaizhang** [comment]
@lierdakil 0.7.11 fixed this. Thanks!

**Comment by lierdakil** [comment]
@kaizhang, please check dev console for warnings and post those here. I'd like to know why it was happening (and maybe report upstream).

**Comment by kaizhang** [comment]
@lierdakil, I don't see any warnings or errors. Everything looks good so far. However, ghc-mod seems to be incompatible with stack. It doesn't search for stack-installed packages. I always get an error of missing libraries when checking my codes. But this is irrelevant.
