### ISSUE TITLE
retrieval of the cabal configuration flags failed

### ISSUE THREAD

**Issue by jgcoded** [atom-haskell/haskell-ghc-mod#33]
Hello, I get the following error when I start up Atom: 

[retrieval of the cabal configuration flags failed: extractField: failed extracting configFlags from input, input contained `configFlags'? False](http://imgur.com/Ksk4Cu1.png)

Here is the console output from Atom: http://i.imgur.com/9yOnQgZ.png

Let me know if I can provide any other information.

**Comment by lierdakil** [comment]
This seems like ghc-mod is complaining about cabal misconfiguration. You might consider running `cabal clean` and `cabal configure` in your project directory.

Also note that ghc-mod from Hackage doesn't work with cabal 1.22 and up, you need to build from git. For more info, see https://github.com/atom-haskell/haskell-ghc-mod/issues/18

If you believe this is a problem with this package, in haskell-ghc-mod settings, enable 'Debug' option, then reproduce this error and post console contents here. Thanks.

**Comment by jgcoded** [comment]
I was using the wrong version of cabal.
