### ISSUE TITLE
Type popups take several seconds to appear when ghc-modi is enabled

### ISSUE THREAD

**Issue by rgleichman** [atom-haskell/haskell-ghc-mod#34]
I am running:
Atom 1.0.2
haskell-ghc-mod 0.8.3
ide-haskell 0.6.2
ghc-mod version 5.2.1.2 compiled by GHC 7.8.4
GHC 7.8.4
Ubuntu 14.04

When ghc-modi is enabled in the haskell-ghc-mod Atom settings, it takes several seconds for the type to popup after hovering over some text. During this time the hourglass appears in the Haskell IDE panel. When the type finally appears, the hourglass turns back into a check-mark. Disabling ghc-modi fixes this; type popups appear promptly with the hourglass appearing for less than a second.

**Comment by lierdakil** [comment]
I don't see how that would be possible. You sure you didn't confuse "enabled" with "disabled"? 'cause expected behavior is entirely backwards. FYI, ghc-modi is enabled by default.

If this really happens the way you describe, an isolated test case would help. Thanks

**Comment by rgleichman** [comment]
It is definitely only slow when ghc-modi is enabled. Yes, gch-modi was enabled by default, so it was slow until I found the setting to disable it. I tried to duplicate this issue with a single standalone file (no Cabal), but type popups appeared promptly regardless of whether ghc-modi was enabled or disabled.

**Comment by lierdakil** [comment]
Sorry about disappointing lack of activity, I was very busy lately. Would you mind providing at least some test case for this? Because for me, on big projects (e.g. ghc-mod or pandoc) type popups are unbearably slow with ghc-modi *disabled* (and that's expected).

**Comment by rgleichman** [comment]
After reinstalling everything today, I do not have this issue.
