### ISSUE TITLE
ghc-mod fails (invalid byte sequence)

### ISSUE THREAD

**Issue by JustusAdam** [atom-haskell/haskell-ghc-mod#35]
Haskell-ghc-mod: ghc-mod failed with error code 1 
    /Users/justusadam/projects/Haskell/vocab-trainer/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

ghc-mod version 5.2.1.2

ghc version 7.8.4

**Comment by lierdakil** [comment]
Please see https://github.com/atom-haskell/ide-haskell/issues/31

**Comment by lierdakil** [comment]
TL;DR: ghc-mod on Hackage doesn't work with cabal-1.22. Downgrade cabal, or build ghc-mod from repo. See https://github.com/atom-haskell/haskell-ghc-mod/issues/18 for information on ghc-mod-master support.

**Comment by JustusAdam** [comment]
fixed by newer version of ghc-mod.
