### ISSUE TITLE
Call unkonwn  -d param with ghc-mod (5.2.1.2)

### ISSUE THREAD

**Issue by whtoo** [atom-haskell/haskell-ghc-mod#39]
Error:
Haskell-ghc-mod: /Users/arthur/.cabal/bin/ghc-mod -d Prelude failed with error code 1

please check it.

**Comment by lierdakil** [comment]
There is a little error in source code that gobbles actual command in error reporting (just fixed with 0.8.8), so it actually calls `ghc-mod browse -d Prelude` I believe. So I think there is another reason why ghc-mod fails for you. Could you provide more details w.r.t. your setup?

**Comment by whtoo** [comment]
Sorry I can't upload my setting on current network.I will post it after work.Thanks.

**Comment by whtoo** [comment]
![ax](https://cloud.githubusercontent.com/assets/909131/9129471/b45bd00a-3d0a-11e5-9ba5-6a60c3fc0a44.png)

**Comment by lierdakil** [comment]
Since you have `Debug` enabled anyway, would you also be kind enough to post dev.console output? (Atom Menu -> View -> Developer -> Toggle Developer Tools -> Console)

**Comment by whtoo** [comment]
![2015-08-10 8 55 08 1](https://cloud.githubusercontent.com/assets/909131/9157800/872ac9d0-3f3d-11e5-9227-9d65f283a530.png)

**Comment by whtoo** [comment]
Haskell-ghc-mod: /Users/arthur/.cabal/bin/ghc-mod browse -d Main failed with error code 1
user error (ghc not found)
Close All
Haskell-ghc-mod: /Users/arthur/.cabal/bin/ghc-mod browse -d Prelude failed with error code 1

**Comment by lierdakil** [comment]
Try adding path to `ghc` to 'Additional Path Directories' (e.g. if `which ghc` gives `/usr/local/bin/ghc`, add `/usr/local/bin` to 'Additional Path Directories').

**Comment by whtoo** [comment]
Thx,I fix this by re-build all haskell-framwork again.And it works fine.
