### ISSUE TITLE
ghc-mod spawn errors

### ISSUE THREAD

**Issue by missingfaktor** [atom-haskell/haskell-ghc-mod#40]
Hello, good people.

Atom fails to spawn ghc-mod for me. 

Error message:

```
/Users/rahulgomaphulore/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `ghc-mod`. Make sure `ghc-mod` is installed and on your PATH
```

I am on OS X, but starting Atom from console.

Here's my `~/.atom/config.cson`:

```
"*":
  "exception-reporting":
    userId: "526c136c-f715-ee5d-1def-7846da50cf76"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
  ghcModPath: "/Users/rahulgomaphulore/.cabal/bin/ghc-mod"
  ghcModiPath: "/Users/rahulgomaphulore/.cabal/bin/ghc-modi"
  additionalPathDirectories: "/Users/rahulgomaphulore/.cabal/bin/"
```

Here's a relevant chunk from my `~/.zshrc`:

```
alias ghc-mod="~/.cabal/bin/ghc-mod"
alias ghc-modi="~/.cabal/bin/ghc-modi"
export ghcModPath="~/.cabal/bin/ghc-mod"
export ghcModiPath="~/.cabal/bin/ghc-modi"
```

As you can see, I am putting these settings pretty much everywhere, but nothing makes it work. :(

**Comment by lierdakil** [comment]
Okay... First, I assume that you're using Atom 1.0.5 (or later, for posterity). Second, your config is not correct. You shouldn't really write it by-hand -- open Edit → Preferences → Packages → Find haskell-ghc-mod → press Settings → put your settings in there.

While you can write config directly, I would strongly advise against that. Anyway, here is an example:
```cson
"*":
  # <...snip...>
  "haskell-ghc-mod":
    additionalPathDirectories: [
      "/usr/bin"
      "/home/livid/github/ghc-mod/.cabal-sandbox/bin"
    ]
    ghcModPath: "..."
    ghcModiPath: "..."
```

**Comment by lierdakil** [comment]
P.S. aliases and environment variables in zshrc don't do anything good in this context, please consider removing them.

**Comment by missingfaktor** [comment]
That fixed it. Thanks @lierdakil! :) 

And thank you for creating this awesome tool. It would be lovely if you could create a video of your workflow with this plugin, but I might be asking for too much!
