### ISSUE TITLE
hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by jasonkuhrt** [atom-haskell/haskell-ghc-mod#42]
<img width="475" alt="screen shot 2015-08-11 at 10 07 24 pm" src="https://cloud.githubusercontent.com/assets/284476/9215209/7ab41e70-4075-11e5-833b-5b2679710421.png">

I was able to google this error but it seems to have many varied cases. I was hoping someone here has direct insight into why I'm experiencing this. Thanks!

**Comment by lierdakil** [comment]
Cabal 1.22.0 and up is not supported with current ghc-mod. If you're using ghc 7.8, downgrade cabal and cabal-install. If you're using ghc 7.10, consider building ghc-mod from git. Also see #18 w.r.t. ghc-mod git version support.

**Comment by jasonkuhrt** [comment]
Thanks, I'll look into possibly building from master.
