### ISSUE TITLE
Error crash

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/haskell-ghc-mod#51]
Haskell-ghc-mod: ghc-modi crashed on type with message 9 11 9 34 "WidgetT App IO (Route App -> [(Text, Text)] -> Text)"

No idea why

**Comment by lierdakil** [comment]
Could you specify ghc-mod version? Also please check if v0.9.1 fixes this.

If you can't reproduce it, I'd suspect some race condition in ghc-mod -- ghc-mod-5.4.0.0 should probably fix it. If you're already using ghc-mod-5.4.0.0, try haskell-ghc-mod-0.9.1 (there are some quirks that had to be worked out with 5.4.0.0). If you're already using both, and *can* reproduce this, I will need more information, or a testcase, or something.

**Comment by wolftune** [comment]
I clarified it is happening in a context that is template haskell related specifically

I still got the error with 0.9.1, and I'm already on ghc-mod-5.4.0.0

This is reproducible consistently. I just hover over the line `$(widgetFile "blah")` in a Yesod Handler

**Comment by lierdakil** [comment]
Sorry, I'm not terribly familiar with Yesod. Is there a git repo I can test this on, or something like that?

**Comment by wolftune** [comment]
the project I'm working on would work, it's public and free/libre/open, but it's a large project, so not ideal for quick testing. https://github.com/yesodweb/yesodweb.com might be a decent option. Any of the files in the code that have `widgetFile` in them should be comparable…

Note: when I had been using ghc-mod 5.3.0.0 git version last week and had installed it with cabal instead of stack and had the older haskell-ghc-mod, I did *not* get this crash. So this is something new.

**Comment by lierdakil** [comment]
Okay, 0.9.3 should work here. This was caused by ghc-mod overflowing internal buffer, so its response was truncated. Hopefully, new code will be more robust.
