### ISSUE TITLE
path to ghc-mod doesn't respect `~`

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/haskell-ghc-mod#55]
If I have ghc-mod in `~/.local/bin/ghc-mod` entering that in the path fails to work in haskell-ghc-mod, while `/home/aaron/.local/bin/ghc-mod` (which is the same place) works.

I'm on Ubuntu 14.04 btw

**Comment by lierdakil** [comment]
Shell expansions are not supported in Atom, due to reasons of cross-platform support and whatnot.

**Comment by wolftune** [comment]
Ok, thanks for the update
