### ISSUE TITLE
Deps aren't detected for test-suite when using stack

### ISSUE THREAD

**Issue by altaic** [atom-haskell/haskell-ghc-mod#57]
Any dependencies unique to the test-suite aren't detected by `haskell-ghc-mod` while using stack, thus producing erroneous `import` errors. The workaround is to additionally use a cabal sandbox.

**Comment by lierdakil** [comment]
At first glance this looks like ghc-mod problem. @DanielG, thoughts?

**Comment by DanielG** [comment]
Hmm you probably need to run `stack test` or something first so it does the equivalent of `--enable-test`. Not sure how stack handles this to be honest.

**Comment by altaic** [comment]
I've been rigorously using my test-suite, so I can verify that running `stack test` does __not__ fix the problem.

**Comment by lierdakil** [comment]
ghc-mod 5.5.0.0 seems to pick those up just fine, so I think this was fixed upstream. Closing.
