### ISSUE TITLE
Ligatures-font Hasklig in Atom 1.1.0 breaks type/info of selected symbol

### ISSUE THREAD

**Issue by clojj** [atom-haskell/haskell-ghc-mod#62]
The ligature <$>  isn't recognized... instead :info of '<' is shown

![wrong-symbol]
(https://cloud.githubusercontent.com/assets/4367963/10954264/ba335448-834c-11e5-9849-f0561f5674f0.png)

Depending on selection or cursor-position, the result differs.
If the selection is extended one char to either side of the ligature, :info is correct !

![screen shot 2015-11-04 at 23 44 56](https://cloud.githubusercontent.com/assets/4367963/10954511/1ff63c4a-834e-11e5-81c3-9d112304ced4.png)

**Comment by lierdakil** [comment]
This is a problem with Atom's rendering of ligatures. Namely, while it shows whole ligature selected, it actually selects only first character (`<` in this case). You can verify this by selecting a ligature and copy-pasting it.

You can select whole ligature (or part of it) with keyboard, but there is no visual confirmation. I believe monoid font doesn't suffer this problem.

![image](https://cloud.githubusercontent.com/assets/7275622/10967993/8f07d374-83cf-11e5-807a-a2e8ba0ce040.png)![image](https://cloud.githubusercontent.com/assets/7275622/10968007/9d98bf84-83cf-11e5-9075-979dbf8f89ea.png)![image](https://cloud.githubusercontent.com/assets/7275622/10968016/ab8f6c28-83cf-11e5-93b0-49b94bc101b5.png)

**Comment by clojj** [comment]
Fira Code does not have this problem.
Ok, so this is probably a font-thing ?

Anyway, as more ligatures fonts will be used in the atom community, any issues with atom's font-handling will hopefully be resolved.

Because other fonts work well, I dont know if any issue should be filed in Atom's core repository.....?

Othewise, to me it looks ok to close this issue!

**Comment by lierdakil** [comment]
Well, opening an issue in Atom core repo can't hurt, and selecting whole ligature representation if ligature is selected seems like reasonable solution.

**Comment by lierdakil** [comment]
Not sure if it would be easy to implement though.
