### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by MrVPlussOne** [atom-haskell/haskell-ghc-mod#63]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of null

```
At /Users/weijiayi/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:163

TypeError: Cannot read property 'toString' of null
  at Socket.<anonymous> (/Users/weijiayi/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process-base.coffee:163:41)
  at Socket.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at Socket.emit (events.js:166:7)
  at emitReadable_ (_stream_readable.js:407:10)
  at emitReadable (_stream_readable.js:401:7)
  at onEofChunk (_stream_readable.js:386:3)
  at readableAddChunk (_stream_readable.js:129:5)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:552:8)

```

### Commands

```
     -0:12.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {},
  "haskell-ghc-mod": {
    "onChangeCheck": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.1
haskell-ghc-mod, v1.1.1
ide-haskell, v1.3.0
ide-haskell-cabal, v1.0.0
language-haskell, v1.4.12

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Do you get this consistently, or is it a once-in-a-while issue?

**Comment by lierdakil** [comment]
Anyway, 1.1.2 shouldn't throw this error, instead providing somewhat more readable error message. If it pops up, please let me know.

**Comment by kavigupta** [comment]
I have the same issue with Atom 1.3.2.

I'm running out of a sandbox, if that has anything to do with it.

**Comment by lierdakil** [comment]
@kavigupta, you can't get this same issue, since there are literally no `toString` calls in that code anymore. Please open new issue (or, if Atom doesn't let you, copy error report by clicking on little clipboard icon and paste it somewhere).

I will close this issue now.
