### ISSUE TITLE
Atom doesn't respond after first character typed if ghc-mod can't be found

### ISSUE THREAD

**Issue by szdavid92** [atom-haskell/haskell-ghc-mod#64]
The plugin doesn't find ghc-mod:
`Haskell-ghc-mod: ghc-mod lang failed with error message Error: spawn ghc-mod ENOENT`

Steps to reproduce:
1. Open a new file an set language to Haskell.
2. Type a character.
The editor doesn't respond anymore.
I also have the autocomplete-haskell plugin installed.

**Comment by szdavid92** [comment]
Even worse if `ghc-mod` is configured. The editor hangs after choosing the language.
I have ghc-mod version 5.3.0.0 compiled by GHC 7.10.2

**Comment by szdavid92** [comment]
However it doesn't seem to be any problem with ghc-mod version 5.4.0.0

**Comment by lierdakil** [comment]
FYI, ghc-mod 5.3.0.0 isn't supported:

> Supported ghc-mod versions are from 4.1.0 to 5.2.1.2, and 5.4.x. 5.3.x might work, but is not officially supported.

That said, I'm frankly baffled at your report of Atom hanging/editor not responding, this should *never* happen. What Atom version do you use? On what OS?

**Comment by szdavid92** [comment]
I'm using Atom 1.1.0 on Linux arch 4.2.4-1-ARCH #1 SMP PREEMPT Fri Oct 23 07:32:38 CEST 2015 x86_64 GNU/Linux

**Comment by szdavid92** [comment]
> Supported ghc-mod versions are from 4.1.0 to 5.2.1.2, and 5.4.x. 5.3.x might work, but is not officially > supported.
I see,  but it hangs too when it can't find ghc-mod.

**Comment by lierdakil** [comment]
Do you have `ide-haskell` plugin installed?

**Comment by lierdakil** [comment]
Nevermind, I was able to reproduce this. Weird. I'll look into this. Thanks for reporting.

**Comment by lierdakil** [comment]
Should be fixed in 1.1.3.
