### ISSUE TITLE
Insert import is not working when file doesn't compile (so not when we want to use it)

### ISSUE THREAD

**Issue by rvion** [atom-haskell/haskell-ghc-mod#68]
Insert import is not working when file doesn't compile (so not when we want to use it)

here forM_ is not in scope, and I can't use insert import to import it

```haskell
module Main where

main :: IO ()
main = do
  putStrLn ("hello world")
  forM_ [1,2] $ \x -> print x
  return ()

```

when it's already in scope, however, I can reimport It

```haskell
module Main where
import           Control.Monad
import Control.Monad -- added by insert import

main :: IO ()
main = do
  putStrLn ("hello world")
  forM_ [1,2] $ \x -> print x
  return ()
```

in case it matters, I use aoto-reformat code with stylish haskell

**Comment by lierdakil** [comment]
You need at least one import to insert new ones. Yes, I know it's not ideal. I will try to fix it down the line, but wasn't able to yet.
