### ISSUE TITLE
ghc 7.10.3: message: Not a number ""

### ISSUE THREAD

**Issue by Heather** [atom-haskell/haskell-ghc-mod#76]
Haskell-ghc-mod: ghc-mod interactive command undefined failed with error code 1

URI: F:\P\thridparty\M\Cr\src\Yaml.hs
message: Not a number ""

Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

haskell-ghc-mod atop package 1.2.7

ghc-mod version 5.4.0.0 compiled by GHC 7.10.3

**Comment by lierdakil** [comment]
Apparently you're using git version of ghc-mod. It's not officially supported, but I'd like to figure out what goes wrong here.
If it's not too much trouble, please enable 'Debug' option in haskell-ghc-mod settings, reproduce this error, and post dev.console output somewhere (or you can directly mail it to me -- see my GitHub profile)

**Comment by lierdakil** [comment]
Since I've updated error reporting capabilities, my previous request doesn't make much sense. If you run into this again, just use Atom's 'create issue' button.
