### ISSUE TITLE
Parse error: on `→` symbol in lambda

### ISSUE THREAD

**Issue by Heather** [atom-haskell/haskell-ghc-mod#91]
for example:

``` haskell
getHTTP :: String    -- url address
         → IO String -- http content
getHTTP url = withSocketsDo
  $ simpleHttp url
      >>= \bs → return $ S.decode $ L.unpack bs
```

error:
```
HTTP.hs: 0, 0
.../src/HTTP.hs: 27: 26:Error:Parse error: $
```

and this one is fine:

``` haskell
getHTTP :: String    -- url address
         → IO String -- http content
getHTTP url = withSocketsDo
  $ simpleHttp url
      >>= \bs -> return $ S.decode $ L.unpack bs
```

master version of ghc-mod: ghc-mod version 5.5.0.0 compiled by GHC 7.10.3, windows 10

not sure if this issue belongs to atom package or ghc-mod itself, mirror: https://github.com/DanielG/ghc-mod/issues/722

**Comment by lierdakil** [comment]
Can't reproduce. Is your file saved or does it only happen on a modified buffer?

**Comment by Heather** [comment]
@lierdakil file is saved, I can reproduce it on several files in several projects

**Comment by lierdakil** [comment]
Seems like ghc-mod issue to me. Probably something to do with system encoding. Could you run ghc-mod from console to make sure? `ghc-mod check \path\to\file.hs` or something like this

**Comment by Heather** [comment]
@lierdakil yes, same issue there

**Comment by rvion** [comment]
@Heather did you open an issue on ghc-mod repo ?

**Comment by lierdakil** [comment]
@rvion, it's mentioned in OP: DanielG/ghc-mod#722

**Comment by rvion** [comment]
woops, my bad, sorry for the noise
