### ISSUE TITLE
Tokenizer error?

### ISSUE THREAD

**Issue by trin-cz** [atom-haskell/haskell-ghc-mod#93]
Howering over multi-char operator shows type only for the one-char operator. As seen below. When howering over '.:' operator, type for '.' operator is shown.
![atom-ghc-mod-multichar-operators](https://cloud.githubusercontent.com/assets/1655137/12267477/9656f854-b948-11e5-815f-6f75cd9c629c.png)

**Comment by lierdakil** [comment]
Today I learned that Atom's `TokenizedBuffer` is a nightmare to work with. v1.5.8 uses mostly home-grown algorithm to find token near buffer position. Hopefully this resolves (most) of the problems. Thanks for reporting.

**Comment by trin-cz** [comment]
Perfect!

I have tried several times since december to get ghc-mod working with stack. First with Intellij and then last week with Atom. All failed for various reasons. Yesterday it was finally working and Haskell programming suddenly got much easier. Finally an actual IDE after all these years (I first started with Haskell in 2008). Great job you're doing!
